name: build
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: fedora:34

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          target: x86_64-pc-windows-gnu
      - run: |
          sudo dnf install -y mingw64-gcc mingw64-pango mingw64-poppler mingw64-gtk3 mingw64-winpthreads-static mingw64-hicolor-icon-theme mingw32-nsis

      - run: make build-windows-release
      - run: make package-windows
      - run: mv installer.exe acd2lr-x86_64-pc-windows-gnu-setup.exe

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: latest
          prerelease: true
          title: "Development Build"
          files: |
            *.exe
